services:
  MongoDB:
    image: mongo:8.0.6
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db:rw
    networks:
      - db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: sample
      MONGO_PORT_NUMBER: 27017

  mongo-express:
    image: mongo-express:1.0.2-18
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    networks:
      - db
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_SITE_BASEURL: /mongo-express
      ME_CONFIG_SITE_PORT: 8081
      ME_CONFIG_SITE_TITLE: Mongo Express

networks:
  db:
    driver: bridge

volumes:
  mongo-data:
    driver: local