services:
  maria-db:
    image: mariadb:11-ubi
    restart: always
    ports:
    - '3306:3306'
    volumes:
      - ./mariadb:/var/lib/mysql:rw
    networks:
      - db
    environment:
      MARIADB_ROOT_PASSWORD: sample-root-password
      MARIADB_USER: sample-user
      MARIADB_PASSWORD: sample-password
      MARIADB_DATABASE: sample
      MARIADB_PORT_NUMBER: 3306

  adminer:
    image: adminer
    restart: always
    networks:
      - db
    ports:
      - 8080:8080

networks:
  db:
    driver: bridge

volumes:
  mariadb_data: