services:
  maria-db:
    image: mariadb:11-ubi
    restart: always
    ports:
    - '3306:3306'
    volumes:
      - ./mariadb:/var/lib/mysql:rw
    networks:
      - db
    environment:
      MARIADB_ROOT_PASSWORD: sample-root-password
      MARIADB_USER: sample-user
      MARIADB_PASSWORD: sample-password
      MARIADB_DATABASE: sample
      MARIADB_PORT_NUMBER: 3306

  oracle-db:
    image: container-registry.oracle.com/database/free:23.7.0.0-lite
    container_name: oracle-db
    restart: always
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=YourPassword123
    volumes:
      - oracle-db:/opt/oracle/oradata:rw
    networks:
      - db

  postgres-db:
    image: postgres:17
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data:rw
    networks:
      - db
    environment:
      POSTGRES_USER: sample-user
      POSTGRES_PASSWORD: sample-password
      POSTGRES_DB: sample

  adminer:
    image: adminer
    restart: always
    networks:
      - db
    ports:
      - 8080:8080

networks:
  db:
    driver: bridge

volumes:
  mariadb:
  oracle-db:
  postgres: